apiVersion: v1
appVersion: "1.0.23"
version: 1.0.23
description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge via Netcup
name: cert-manager-webhook-netcup
home: https://github.com/aellwein/cert-manager-webhook-netcup
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
keywords:
  - cert-manager
  - webhook
  - letsencrypt
  - netcup
  - ACME
  - DNS01
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Alex Ellwein
      email: alex.ellwein@gmail.com
  artifacthub.io/containsSecurityUpdates: "true"
  # kinds: added, changed, deprecated, removed, fixed, security.
  artifacthub.io/changes: |
    - kind: security
      description: "bump golang.org/x/net to 0.24 to mitigate CVE-2023-45288"
    - kind: changed
      description: "use Go 1.22"
    - kind: changed
      description: "bump apiextensions-apiserver,apimachinery,client-go and other dependencies"
  artifacthub.io/signKey: |
    fingerprint: "F91914CE96676E209A8240290EEF2777053A7D1A"
    url: https://keybase.io/aellwein/pgp_keys.asc
