apiVersion: v1
appVersion: "1.0.22"
version: 1.0.22
description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge via Netcup
name: cert-manager-webhook-netcup
home: https://github.com/aellwein/cert-manager-webhook-netcup
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
keywords:
  - cert-manager
  - webhook
  - letsencrypt
  - netcup
  - ACME
  - DNS01
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Alex Ellwein
      email: alex.ellwein@gmail.com
  artifacthub.io/containsSecurityUpdates: "true"
  # kinds: added, changed, deprecated, removed, fixed, security.
  artifacthub.io/changes: |
    - kind: changed
      description: "bump k8s.io/apiextensions-apiserver from 0.29.2 to 0.29.3"
    - kind: changed
      description: "bump k8s.io/apimachinery from 0.29.2 to 0.29.3"
    - kind: changed
      description: "bump k8s.io/client-go from 0.29.2 to 0.29.3"
    - kind: changed
      description: "bump cert-manager to 1.14.4"
    - kind: fixed
      description: "bump dependencies to fix CVE-2024-24786"
  artifacthub.io/signKey: |
    fingerprint: "F91914CE96676E209A8240290EEF2777053A7D1A"
    url: https://keybase.io/aellwein/pgp_keys.asc
