apiVersion: v1
entries:
  cert-manager-webhook-bunny:
    - annotations:
        artifacthub.io/license: Apache-2.0
        artifacthub.io/maintainers: |
          - name: David Hidvegi
            email: david@hidvegi.xyz
      apiVersion: v1
      appVersion: 1.0.1
      created: "2025-01-25T01:26:24.677343+01:00"
      description:
        A Helm chart for cert manager webhook solver for ACME DNS01 challenge
        via Bunny
      digest: b777d423cb607c368084fabf251834728bfaa94e4a0e8c6a6efc1b444f8c89d4
      home: https://github.com/davidhidvegi/cert-manager-webhook-bunny
      icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
      keywords:
        - cert-manager
        - webhook
        - letsencrypt
        - bunny
        - ACME
        - DNS01
      name: cert-manager-webhook-bunny
      urls:
        - cert-manager-webhook-bunny-1.0.1.tgz
      version: 1.0.1
    - annotations:
        artifacthub.io/license: Apache-2.0
        artifacthub.io/maintainers: |
          - name: David Hidvegi
            email: david@hidvegi.xyz
      apiVersion: v1
      appVersion: 1.0.2
      created: "2026-02-26T14:42:43.826423+01:00"
      description:
        A Helm chart for cert manager webhook solver for ACME DNS01 challenge
        via Bunny
      digest: 47db7562df4453e7ca7255fe7415486d7bcd02f3
      home: https://github.com/davidhidvegi/cert-manager-webhook-bunny
      icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
      keywords:
        - cert-manager
        - webhook
        - letsencrypt
        - bunny
        - ACME
        - DNS01
      name: cert-manager-webhook-bunny
      urls:
        - cert-manager-webhook-bunny-1.0.2.tgz
      version: 1.0.2
generated: "2025-01-25T01:26:24.676871+01:00"
