apiVersion: v1
entries:
  cert-manager-webhook-netcup:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: "Use updated base Docker image (alpine 3.17.2) to mitigate CVEs in openssl and libcrypto3"
        - kind: fixed
          description: "openssl CVE-2023-0286"
        - kind: fixed
          description: "openssl CVE-2022-4304"
        - kind: fixed
          description: "openssl CVE-2022-4203"
        - kind: fixed
          description: "openssl CVE-2023-0215"
        - kind: fixed
          description: "openssl CVE-2022-4450"
        - kind: fixed
          description: "openssl CVE-2023-0216"
        - kind: fixed
          description: "openssl CVE-2023-0217"
        - kind: fixed
          description: "openssl CVE-2023-0401"
        - kind: fixed
          description: "libcrypto3 CVE-2023-0286"
        - kind: fixed
          description: "libcrypto3 CVE-2022-4203"
        - kind: fixed
          description: "libcrypto3 CVE-2022-4304"
        - kind: fixed
          description: "libcrypto3 CVE-2022-4450"
        - kind: fixed
          description: "libcrypto3 CVE-2023-0215"
        - kind: fixed
          description: "libcrypto3 CVE-2023-0216"
        - kind: fixed
          description: "libcrypto3 CVE-2023-0217"
        - kind: fixed
          description: "libcrypto3 CVE-2023-0401"
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/license: Apache-2.0
      artifacthub.io/maintainers: |
        - name: Alex Ellwein
          email: alex.ellwein@gmail.com
    apiVersion: v1
    appVersion: 1.0.12
    created: "2023-02-15T19:09:20.78169+01:00"
    description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge
      via Netcup
    digest: bede761557c38f373c3923f9d9128f77c8fc32d2b1d79f1fda4cb548c031f62d
    home: https://github.com/aellwein/cert-manager-webhook-netcup
    icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - webhook
    - letsencrypt
    - netcup
    - ACME
    - DNS01
    name: cert-manager-webhook-netcup
    urls:
    - cert-manager-webhook-netcup-1.0.12.tgz
    version: 1.0.12
  - annotations:
      artifacthub.io/changes: |
        - Use updated base Docker image (alpine 3.17.1) mitigate [CVE-2022-3996](https://github.com/advisories/GHSA-vr8j-hgmm-jh9r)
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/license: Apache-2.0
      artifacthub.io/maintainers: |
        - name: Alex Ellwein
          email: alex.ellwein@gmail.com
    apiVersion: v1
    appVersion: 1.0.11
    created: "2023-02-15T19:09:20.781347+01:00"
    description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge
      via Netcup
    digest: aa66de90af78012c0521d3ec48265746ee97f26640248e4b68328331c4ce6f2d
    home: https://github.com/aellwein/cert-manager-webhook-netcup
    icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - webhook
    - letsencrypt
    - netcup
    - ACME
    - DNS01
    name: cert-manager-webhook-netcup
    urls:
    - cert-manager-webhook-netcup-1.0.11.tgz
    version: 1.0.11
  - annotations:
      artifacthub.io/changes: |
        - Use updated deps to mitigate [CVE-2022-41717](https://nvd.nist.gov/vuln/detail/CVE-2022-41717)
        - Use Go 1.19 and alpine 3.17 Docker image
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/license: Apache-2.0
      artifacthub.io/maintainers: |
        - name: Alex Ellwein
          email: alex.ellwein@gmail.com
    apiVersion: v1
    appVersion: 1.0.10
    created: "2023-02-15T19:09:20.78103+01:00"
    description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge
      via Netcup
    digest: f6ec08186bf14c204eef0971e9c84545b5a8bb3d455d7cdcca488ddc71830695
    home: https://github.com/aellwein/cert-manager-webhook-netcup
    icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - webhook
    - letsencrypt
    - netcup
    - ACME
    - DNS01
    name: cert-manager-webhook-netcup
    urls:
    - cert-manager-webhook-netcup-1.0.10.tgz
    version: 1.0.10
  - annotations:
      artifacthub.io/changes: |
        - Mitigation for CVE-2022-32149
        - README and annotations in chart for ArtifactHub
        - Possibility to use digest (image hash) in values.yml
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/license: Apache-2.0
      artifacthub.io/maintainers: |
        - name: Alex Ellwein
          email: alex.ellwein@gmail.com
    apiVersion: v1
    appVersion: 1.0.9
    created: "2023-02-15T19:09:20.78365+01:00"
    description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge
      via Netcup
    digest: d3b6eab27e21af3ae6fb5473e4b0e5db8d75c95bf5ee9b7f1b2e25e98b488bd3
    home: https://github.com/aellwein/cert-manager-webhook-netcup
    icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - webhook
    - letsencrypt
    - netcup
    - ACME
    - DNS01
    name: cert-manager-webhook-netcup
    urls:
    - cert-manager-webhook-netcup-1.0.9.tgz
    version: 1.0.9
  - apiVersion: v1
    appVersion: 1.0.8
    created: "2023-02-15T19:09:20.783344+01:00"
    description: Allow cert-manager to solve DNS challenges using Netcup DNS API
    digest: 4b1c49ef9ab1c57428cff35824dd7cb13f187af74fa7dcd560dd788aa0dce892
    name: cert-manager-webhook-netcup
    urls:
    - cert-manager-webhook-netcup-1.0.8.tgz
    version: 1.0.8
  - apiVersion: v1
    appVersion: 1.0.7
    created: "2023-02-15T19:09:20.782575+01:00"
    description: Allow cert-manager to solve DNS challenges using Netcup DNS API
    digest: 0d262079f7326e41020df239298f5106bebaf9d797a9ce61550caa6457237a69
    name: cert-manager-webhook-netcup
    urls:
    - cert-manager-webhook-netcup-1.0.7.tgz
    version: 1.0.7
  - apiVersion: v1
    appVersion: 1.0.6
    created: "2023-02-15T19:09:20.782372+01:00"
    description: Allow cert-manager to solve DNS challenges using Netcup DNS API
    digest: f1eb0f11758d480a6fa187a54cdca8669b1ccdb75f022b53d84253723827b7c7
    name: cert-manager-webhook-netcup
    urls:
    - cert-manager-webhook-netcup-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v1
    appVersion: 1.0.5
    created: "2023-02-15T19:09:20.78215+01:00"
    description: Allow cert-manager to solve DNS challenges using Netcup DNS API
    digest: 24df7547c2509b06972440c318a22e7e62c0c00c55a796b2c71b70c2e6a1f9bf
    name: cert-manager-webhook-netcup
    urls:
    - cert-manager-webhook-netcup-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v1
    appVersion: 1.0.3
    created: "2023-02-15T19:09:20.781924+01:00"
    description: Allow cert-manager to solve DNS challenges using Netcup DNS API
    digest: 03f7f124bb6d76a606a9ed598466b1f4aa422c4406bde52cfff1202a209cd9fd
    name: cert-manager-webhook-netcup
    urls:
    - cert-manager-webhook-netcup-1.0.3.tgz
    version: 1.0.3
generated: "2023-02-15T19:09:20.780621+01:00"
