name: Build Docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Preapre new buildx context
        run: docker buildx create --use

      - name: Build & push Docker image (all architectures)
        if: github.ref == 'refs/heads/master'
        run: |
          make build-and-push

      - name: Build & push Docker image (amd64 only for develop)
        # only build amd64 version on develop to speed things up
        if: github.ref == 'refs/heads/develop'
        run: |
          make build-local
